// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnzyrxijyoepiqjhicrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImduenlyeGlqeW9lcGlxamhpY3JkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MTY0MTMsImV4cCI6MjA1NzE5MjQxM30.EUyyjxJhDPnXbOjPerR7HvNOWZhQI8LAC-pwGV-R0_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);