// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trfwilvnzgzicebljowa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyZndpbHZuemd6aWNlYmxqb3dhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1NzM0MjQsImV4cCI6MjA3NzE0OTQyNH0.ULUWfwFnjnvG8XL_VrkS-9KCPUO8qr3Drgsq-Umk1UE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});